// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: api/proto/hurricane.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NodeStatus int32

const (
	NodeStatus_NODE_UNKNOWN NodeStatus = 0
	NodeStatus_NODE_ONLINE  NodeStatus = 1
	NodeStatus_NODE_READY   NodeStatus = 2
	NodeStatus_NODE_RUNNING NodeStatus = 3
	NodeStatus_NODE_ERROR   NodeStatus = 4
)

// Enum value maps for NodeStatus.
var (
	NodeStatus_name = map[int32]string{
		0: "NODE_UNKNOWN",
		1: "NODE_ONLINE",
		2: "NODE_READY",
		3: "NODE_RUNNING",
		4: "NODE_ERROR",
	}
	NodeStatus_value = map[string]int32{
		"NODE_UNKNOWN": 0,
		"NODE_ONLINE":  1,
		"NODE_READY":   2,
		"NODE_RUNNING": 3,
		"NODE_ERROR":   4,
	}
)

func (x NodeStatus) Enum() *NodeStatus {
	p := new(NodeStatus)
	*p = x
	return p
}

func (x NodeStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NodeStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_hurricane_proto_enumTypes[0].Descriptor()
}

func (NodeStatus) Type() protoreflect.EnumType {
	return &file_api_proto_hurricane_proto_enumTypes[0]
}

func (x NodeStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NodeStatus.Descriptor instead.
func (NodeStatus) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_hurricane_proto_rawDescGZIP(), []int{0}
}

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Addr          string                 `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	Workers       int32                  `protobuf:"varint,3,opt,name=workers,proto3" json:"workers,omitempty"`
	MemoryMb      int64                  `protobuf:"varint,4,opt,name=memory_mb,json=memoryMb,proto3" json:"memory_mb,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_api_proto_hurricane_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_hurricane_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_hurricane_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *RegisterRequest) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *RegisterRequest) GetWorkers() int32 {
	if x != nil {
		return x.Workers
	}
	return 0
}

func (x *RegisterRequest) GetMemoryMb() int64 {
	if x != nil {
		return x.MemoryMb
	}
	return 0
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_api_proto_hurricane_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_hurricane_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_hurricane_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *RegisterResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Status        NodeStatus             `protobuf:"varint,3,opt,name=status,proto3,enum=hurricane.NodeStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_api_proto_hurricane_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_hurricane_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_hurricane_proto_rawDescGZIP(), []int{2}
}

func (x *HeartbeatRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *HeartbeatRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *HeartbeatRequest) GetStatus() NodeStatus {
	if x != nil {
		return x.Status
	}
	return NodeStatus_NODE_UNKNOWN
}

type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_api_proto_hurricane_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_hurricane_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_hurricane_proto_rawDescGZIP(), []int{3}
}

func (x *HeartbeatResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type DeployRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Target        *TargetConfig          `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	Engine        *EngineConfig          `protobuf:"bytes,3,opt,name=engine,proto3" json:"engine,omitempty"`
	NodeIds       []string               `protobuf:"bytes,4,rep,name=node_ids,json=nodeIds,proto3" json:"node_ids,omitempty"` // empty = all ready nodes
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeployRequest) Reset() {
	*x = DeployRequest{}
	mi := &file_api_proto_hurricane_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeployRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeployRequest) ProtoMessage() {}

func (x *DeployRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_hurricane_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeployRequest.ProtoReflect.Descriptor instead.
func (*DeployRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_hurricane_proto_rawDescGZIP(), []int{4}
}

func (x *DeployRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *DeployRequest) GetTarget() *TargetConfig {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *DeployRequest) GetEngine() *EngineConfig {
	if x != nil {
		return x.Engine
	}
	return nil
}

func (x *DeployRequest) GetNodeIds() []string {
	if x != nil {
		return x.NodeIds
	}
	return nil
}

type DeployResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	TaskId        string                 `protobuf:"bytes,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeployResponse) Reset() {
	*x = DeployResponse{}
	mi := &file_api_proto_hurricane_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeployResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeployResponse) ProtoMessage() {}

func (x *DeployResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_hurricane_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeployResponse.ProtoReflect.Descriptor instead.
func (*DeployResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_hurricane_proto_rawDescGZIP(), []int{5}
}

func (x *DeployResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *DeployResponse) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *DeployResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type StopRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopRequest) Reset() {
	*x = StopRequest{}
	mi := &file_api_proto_hurricane_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopRequest) ProtoMessage() {}

func (x *StopRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_hurricane_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopRequest.ProtoReflect.Descriptor instead.
func (*StopRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_hurricane_proto_rawDescGZIP(), []int{6}
}

func (x *StopRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type StopResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopResponse) Reset() {
	*x = StopResponse{}
	mi := &file_api_proto_hurricane_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopResponse) ProtoMessage() {}

func (x *StopResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_hurricane_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopResponse.ProtoReflect.Descriptor instead.
func (*StopResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_hurricane_proto_rawDescGZIP(), []int{7}
}

func (x *StopResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_api_proto_hurricane_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_hurricane_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_hurricane_proto_rawDescGZIP(), []int{8}
}

func (x *StatusRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type StatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	State         string                 `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"` // "pending", "running", "completed", "failed"
	Nodes         []*NodeTaskStatus      `protobuf:"bytes,3,rep,name=nodes,proto3" json:"nodes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_api_proto_hurricane_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_hurricane_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_hurricane_proto_rawDescGZIP(), []int{9}
}

func (x *StatusResponse) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *StatusResponse) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *StatusResponse) GetNodes() []*NodeTaskStatus {
	if x != nil {
		return x.Nodes
	}
	return nil
}

type NodeTaskStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	State         string                 `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	Connections   int64                  `protobuf:"varint,3,opt,name=connections,proto3" json:"connections,omitempty"`
	Cps           int64                  `protobuf:"varint,4,opt,name=cps,proto3" json:"cps,omitempty"`
	BytesSent     int64                  `protobuf:"varint,5,opt,name=bytes_sent,json=bytesSent,proto3" json:"bytes_sent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeTaskStatus) Reset() {
	*x = NodeTaskStatus{}
	mi := &file_api_proto_hurricane_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeTaskStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeTaskStatus) ProtoMessage() {}

func (x *NodeTaskStatus) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_hurricane_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeTaskStatus.ProtoReflect.Descriptor instead.
func (*NodeTaskStatus) Descriptor() ([]byte, []int) {
	return file_api_proto_hurricane_proto_rawDescGZIP(), []int{10}
}

func (x *NodeTaskStatus) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *NodeTaskStatus) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *NodeTaskStatus) GetConnections() int64 {
	if x != nil {
		return x.Connections
	}
	return 0
}

func (x *NodeTaskStatus) GetCps() int64 {
	if x != nil {
		return x.Cps
	}
	return 0
}

func (x *NodeTaskStatus) GetBytesSent() int64 {
	if x != nil {
		return x.BytesSent
	}
	return 0
}

type TargetConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Host          string                 `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Port          int32                  `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	Tls           bool                   `protobuf:"varint,3,opt,name=tls,proto3" json:"tls,omitempty"`
	Path          string                 `protobuf:"bytes,4,opt,name=path,proto3" json:"path,omitempty"`
	Method        string                 `protobuf:"bytes,5,opt,name=method,proto3" json:"method,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TargetConfig) Reset() {
	*x = TargetConfig{}
	mi := &file_api_proto_hurricane_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TargetConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TargetConfig) ProtoMessage() {}

func (x *TargetConfig) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_hurricane_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TargetConfig.ProtoReflect.Descriptor instead.
func (*TargetConfig) Descriptor() ([]byte, []int) {
	return file_api_proto_hurricane_proto_rawDescGZIP(), []int{11}
}

func (x *TargetConfig) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *TargetConfig) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *TargetConfig) GetTls() bool {
	if x != nil {
		return x.Tls
	}
	return false
}

func (x *TargetConfig) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *TargetConfig) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

type EngineConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Workers       int32                  `protobuf:"varint,1,opt,name=workers,proto3" json:"workers,omitempty"`
	Connections   int32                  `protobuf:"varint,2,opt,name=connections,proto3" json:"connections,omitempty"`
	Cps           int32                  `protobuf:"varint,3,opt,name=cps,proto3" json:"cps,omitempty"`
	DurationSec   int32                  `protobuf:"varint,4,opt,name=duration_sec,json=durationSec,proto3" json:"duration_sec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EngineConfig) Reset() {
	*x = EngineConfig{}
	mi := &file_api_proto_hurricane_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EngineConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EngineConfig) ProtoMessage() {}

func (x *EngineConfig) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_hurricane_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EngineConfig.ProtoReflect.Descriptor instead.
func (*EngineConfig) Descriptor() ([]byte, []int) {
	return file_api_proto_hurricane_proto_rawDescGZIP(), []int{12}
}

func (x *EngineConfig) GetWorkers() int32 {
	if x != nil {
		return x.Workers
	}
	return 0
}

func (x *EngineConfig) GetConnections() int32 {
	if x != nil {
		return x.Connections
	}
	return 0
}

func (x *EngineConfig) GetCps() int32 {
	if x != nil {
		return x.Cps
	}
	return 0
}

func (x *EngineConfig) GetDurationSec() int32 {
	if x != nil {
		return x.DurationSec
	}
	return 0
}

type MetricsReport struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	NodeId            string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Timestamp         int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	ActiveConnections int64                  `protobuf:"varint,3,opt,name=active_connections,json=activeConnections,proto3" json:"active_connections,omitempty"`
	TotalConnections  int64                  `protobuf:"varint,4,opt,name=total_connections,json=totalConnections,proto3" json:"total_connections,omitempty"`
	Cps               int64                  `protobuf:"varint,5,opt,name=cps,proto3" json:"cps,omitempty"`
	BytesSent         int64                  `protobuf:"varint,6,opt,name=bytes_sent,json=bytesSent,proto3" json:"bytes_sent,omitempty"`
	BytesRecv         int64                  `protobuf:"varint,7,opt,name=bytes_recv,json=bytesRecv,proto3" json:"bytes_recv,omitempty"`
	Errors            int64                  `protobuf:"varint,8,opt,name=errors,proto3" json:"errors,omitempty"`
	LatencyAvgUs      float64                `protobuf:"fixed64,9,opt,name=latency_avg_us,json=latencyAvgUs,proto3" json:"latency_avg_us,omitempty"`
	LatencyP99Us      float64                `protobuf:"fixed64,10,opt,name=latency_p99_us,json=latencyP99Us,proto3" json:"latency_p99_us,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *MetricsReport) Reset() {
	*x = MetricsReport{}
	mi := &file_api_proto_hurricane_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsReport) ProtoMessage() {}

func (x *MetricsReport) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_hurricane_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsReport.ProtoReflect.Descriptor instead.
func (*MetricsReport) Descriptor() ([]byte, []int) {
	return file_api_proto_hurricane_proto_rawDescGZIP(), []int{13}
}

func (x *MetricsReport) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *MetricsReport) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *MetricsReport) GetActiveConnections() int64 {
	if x != nil {
		return x.ActiveConnections
	}
	return 0
}

func (x *MetricsReport) GetTotalConnections() int64 {
	if x != nil {
		return x.TotalConnections
	}
	return 0
}

func (x *MetricsReport) GetCps() int64 {
	if x != nil {
		return x.Cps
	}
	return 0
}

func (x *MetricsReport) GetBytesSent() int64 {
	if x != nil {
		return x.BytesSent
	}
	return 0
}

func (x *MetricsReport) GetBytesRecv() int64 {
	if x != nil {
		return x.BytesRecv
	}
	return 0
}

func (x *MetricsReport) GetErrors() int64 {
	if x != nil {
		return x.Errors
	}
	return 0
}

func (x *MetricsReport) GetLatencyAvgUs() float64 {
	if x != nil {
		return x.LatencyAvgUs
	}
	return 0
}

func (x *MetricsReport) GetLatencyP99Us() float64 {
	if x != nil {
		return x.LatencyP99Us
	}
	return 0
}

type MetricsAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricsAck) Reset() {
	*x = MetricsAck{}
	mi := &file_api_proto_hurricane_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsAck) ProtoMessage() {}

func (x *MetricsAck) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_hurricane_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsAck.ProtoReflect.Descriptor instead.
func (*MetricsAck) Descriptor() ([]byte, []int) {
	return file_api_proto_hurricane_proto_rawDescGZIP(), []int{14}
}

func (x *MetricsAck) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

var File_api_proto_hurricane_proto protoreflect.FileDescriptor

const file_api_proto_hurricane_proto_rawDesc = "" +
	"\n" +
	"\x19api/proto/hurricane.proto\x12\thurricane\"u\n" +
	"\x0fRegisterRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x12\n" +
	"\x04addr\x18\x02 \x01(\tR\x04addr\x12\x18\n" +
	"\aworkers\x18\x03 \x01(\x05R\aworkers\x12\x1b\n" +
	"\tmemory_mb\x18\x04 \x01(\x03R\bmemoryMb\"H\n" +
	"\x10RegisterResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"x\n" +
	"\x10HeartbeatRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x12-\n" +
	"\x06status\x18\x03 \x01(\x0e2\x15.hurricane.NodeStatusR\x06status\"#\n" +
	"\x11HeartbeatResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"\xa5\x01\n" +
	"\rDeployRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12/\n" +
	"\x06target\x18\x02 \x01(\v2\x17.hurricane.TargetConfigR\x06target\x12/\n" +
	"\x06engine\x18\x03 \x01(\v2\x17.hurricane.EngineConfigR\x06engine\x12\x19\n" +
	"\bnode_ids\x18\x04 \x03(\tR\anodeIds\"_\n" +
	"\x0eDeployResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x17\n" +
	"\atask_id\x18\x02 \x01(\tR\x06taskId\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"&\n" +
	"\vStopRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\"\x1e\n" +
	"\fStopResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"(\n" +
	"\rStatusRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\"p\n" +
	"\x0eStatusResponse\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x14\n" +
	"\x05state\x18\x02 \x01(\tR\x05state\x12/\n" +
	"\x05nodes\x18\x03 \x03(\v2\x19.hurricane.NodeTaskStatusR\x05nodes\"\x92\x01\n" +
	"\x0eNodeTaskStatus\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x14\n" +
	"\x05state\x18\x02 \x01(\tR\x05state\x12 \n" +
	"\vconnections\x18\x03 \x01(\x03R\vconnections\x12\x10\n" +
	"\x03cps\x18\x04 \x01(\x03R\x03cps\x12\x1d\n" +
	"\n" +
	"bytes_sent\x18\x05 \x01(\x03R\tbytesSent\"t\n" +
	"\fTargetConfig\x12\x12\n" +
	"\x04host\x18\x01 \x01(\tR\x04host\x12\x12\n" +
	"\x04port\x18\x02 \x01(\x05R\x04port\x12\x10\n" +
	"\x03tls\x18\x03 \x01(\bR\x03tls\x12\x12\n" +
	"\x04path\x18\x04 \x01(\tR\x04path\x12\x16\n" +
	"\x06method\x18\x05 \x01(\tR\x06method\"\x7f\n" +
	"\fEngineConfig\x12\x18\n" +
	"\aworkers\x18\x01 \x01(\x05R\aworkers\x12 \n" +
	"\vconnections\x18\x02 \x01(\x05R\vconnections\x12\x10\n" +
	"\x03cps\x18\x03 \x01(\x05R\x03cps\x12!\n" +
	"\fduration_sec\x18\x04 \x01(\x05R\vdurationSec\"\xd6\x02\n" +
	"\rMetricsReport\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x12-\n" +
	"\x12active_connections\x18\x03 \x01(\x03R\x11activeConnections\x12+\n" +
	"\x11total_connections\x18\x04 \x01(\x03R\x10totalConnections\x12\x10\n" +
	"\x03cps\x18\x05 \x01(\x03R\x03cps\x12\x1d\n" +
	"\n" +
	"bytes_sent\x18\x06 \x01(\x03R\tbytesSent\x12\x1d\n" +
	"\n" +
	"bytes_recv\x18\a \x01(\x03R\tbytesRecv\x12\x16\n" +
	"\x06errors\x18\b \x01(\x03R\x06errors\x12$\n" +
	"\x0elatency_avg_us\x18\t \x01(\x01R\flatencyAvgUs\x12$\n" +
	"\x0elatency_p99_us\x18\n" +
	" \x01(\x01R\flatencyP99Us\"\x1c\n" +
	"\n" +
	"MetricsAck\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok*a\n" +
	"\n" +
	"NodeStatus\x12\x10\n" +
	"\fNODE_UNKNOWN\x10\x00\x12\x0f\n" +
	"\vNODE_ONLINE\x10\x01\x12\x0e\n" +
	"\n" +
	"NODE_READY\x10\x02\x12\x10\n" +
	"\fNODE_RUNNING\x10\x03\x12\x0e\n" +
	"\n" +
	"NODE_ERROR\x10\x042\x9a\x01\n" +
	"\vNodeService\x12C\n" +
	"\bRegister\x12\x1a.hurricane.RegisterRequest\x1a\x1b.hurricane.RegisterResponse\x12F\n" +
	"\tHeartbeat\x12\x1b.hurricane.HeartbeatRequest\x1a\x1c.hurricane.HeartbeatResponse2\xc4\x01\n" +
	"\vTaskService\x12=\n" +
	"\x06Deploy\x12\x18.hurricane.DeployRequest\x1a\x19.hurricane.DeployResponse\x127\n" +
	"\x04Stop\x12\x16.hurricane.StopRequest\x1a\x17.hurricane.StopResponse\x12=\n" +
	"\x06Status\x12\x18.hurricane.StatusRequest\x1a\x19.hurricane.StatusResponse2T\n" +
	"\x0eMetricsService\x12B\n" +
	"\rReportMetrics\x12\x18.hurricane.MetricsReport\x1a\x15.hurricane.MetricsAck(\x01B(Z&github.com/kerbos/hurricanex/api/protob\x06proto3"

var (
	file_api_proto_hurricane_proto_rawDescOnce sync.Once
	file_api_proto_hurricane_proto_rawDescData []byte
)

func file_api_proto_hurricane_proto_rawDescGZIP() []byte {
	file_api_proto_hurricane_proto_rawDescOnce.Do(func() {
		file_api_proto_hurricane_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_hurricane_proto_rawDesc), len(file_api_proto_hurricane_proto_rawDesc)))
	})
	return file_api_proto_hurricane_proto_rawDescData
}

var file_api_proto_hurricane_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_proto_hurricane_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_api_proto_hurricane_proto_goTypes = []any{
	(NodeStatus)(0),           // 0: hurricane.NodeStatus
	(*RegisterRequest)(nil),   // 1: hurricane.RegisterRequest
	(*RegisterResponse)(nil),  // 2: hurricane.RegisterResponse
	(*HeartbeatRequest)(nil),  // 3: hurricane.HeartbeatRequest
	(*HeartbeatResponse)(nil), // 4: hurricane.HeartbeatResponse
	(*DeployRequest)(nil),     // 5: hurricane.DeployRequest
	(*DeployResponse)(nil),    // 6: hurricane.DeployResponse
	(*StopRequest)(nil),       // 7: hurricane.StopRequest
	(*StopResponse)(nil),      // 8: hurricane.StopResponse
	(*StatusRequest)(nil),     // 9: hurricane.StatusRequest
	(*StatusResponse)(nil),    // 10: hurricane.StatusResponse
	(*NodeTaskStatus)(nil),    // 11: hurricane.NodeTaskStatus
	(*TargetConfig)(nil),      // 12: hurricane.TargetConfig
	(*EngineConfig)(nil),      // 13: hurricane.EngineConfig
	(*MetricsReport)(nil),     // 14: hurricane.MetricsReport
	(*MetricsAck)(nil),        // 15: hurricane.MetricsAck
}
var file_api_proto_hurricane_proto_depIdxs = []int32{
	0,  // 0: hurricane.HeartbeatRequest.status:type_name -> hurricane.NodeStatus
	12, // 1: hurricane.DeployRequest.target:type_name -> hurricane.TargetConfig
	13, // 2: hurricane.DeployRequest.engine:type_name -> hurricane.EngineConfig
	11, // 3: hurricane.StatusResponse.nodes:type_name -> hurricane.NodeTaskStatus
	1,  // 4: hurricane.NodeService.Register:input_type -> hurricane.RegisterRequest
	3,  // 5: hurricane.NodeService.Heartbeat:input_type -> hurricane.HeartbeatRequest
	5,  // 6: hurricane.TaskService.Deploy:input_type -> hurricane.DeployRequest
	7,  // 7: hurricane.TaskService.Stop:input_type -> hurricane.StopRequest
	9,  // 8: hurricane.TaskService.Status:input_type -> hurricane.StatusRequest
	14, // 9: hurricane.MetricsService.ReportMetrics:input_type -> hurricane.MetricsReport
	2,  // 10: hurricane.NodeService.Register:output_type -> hurricane.RegisterResponse
	4,  // 11: hurricane.NodeService.Heartbeat:output_type -> hurricane.HeartbeatResponse
	6,  // 12: hurricane.TaskService.Deploy:output_type -> hurricane.DeployResponse
	8,  // 13: hurricane.TaskService.Stop:output_type -> hurricane.StopResponse
	10, // 14: hurricane.TaskService.Status:output_type -> hurricane.StatusResponse
	15, // 15: hurricane.MetricsService.ReportMetrics:output_type -> hurricane.MetricsAck
	10, // [10:16] is the sub-list for method output_type
	4,  // [4:10] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_api_proto_hurricane_proto_init() }
func file_api_proto_hurricane_proto_init() {
	if File_api_proto_hurricane_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_hurricane_proto_rawDesc), len(file_api_proto_hurricane_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_api_proto_hurricane_proto_goTypes,
		DependencyIndexes: file_api_proto_hurricane_proto_depIdxs,
		EnumInfos:         file_api_proto_hurricane_proto_enumTypes,
		MessageInfos:      file_api_proto_hurricane_proto_msgTypes,
	}.Build()
	File_api_proto_hurricane_proto = out.File
	file_api_proto_hurricane_proto_goTypes = nil
	file_api_proto_hurricane_proto_depIdxs = nil
}
